### ISSUE TITLE
Avoid use of pre-built wheels during the bootstrap process

### ISSUE THREAD

**Issue by markmc** [markmc/rebuilding-the-wheel#11]
Scenario to consider - an attacker manages to upload a malicious wheel to PyPI, not making any changes to the sdist in the hope that their changes would be obfuscated due to the "binary" nature of the wheel

We will rebuild this wheel from source, so our final repo will not contain this malicious code. We will even rebuild this wheel before it is used to build any later wheels

However, we may have used the wheel in the `mirror-sdists` process in order to get a dependency list that drives the later build process

So, for example, the malicious code could inject a new dependency - perhaps a PyPI project controlled by the attacker - and we would download that sdist and produce a wheel for it.

Simply put, we want to avoid relying on wheels. We want to drive everything from sdists

A first step that might work is to use `pip install --no-binary :all:` in `mirror-sdist.sh` - that way we know that everything we're using in this phase is being built on the fly from sdists?

However, I think it would be better if we instead installed this stuff from our own wheels repo, which presents a bootstrapping challenge

e.g. we could build a relatively minimal wheels repo of build dependencies using the `pip install --no-binary :all:` approach and use that as the starting point for building everything else

We can probably learn from [Fedora mass rebuilds](https://docs.fedoraproject.org/en-US/infra/release_guide/mass_rebuild/) and [bootstrapping new architectures](https://fedoraproject.org/wiki/Architectures/RISC-V/Bootstrapping) but obviously the challenge is orders of magnitude easier - e.g. we don't have to cross-compile a compiler to get started!

**Comment by markmc** [comment]
Probably relevant also: https://docs.fedoraproject.org/en-US/packaging-guidelines/#bootstrapping

**Comment by dhellmann** [comment]
I've found a circular dependency between `hatch-vcs` and `hatchling`.

```
langchain-0.1.13
PyYAML-6.0.1 
setuptools-69.2.0
wheel-0.43.0
pytest-8.1.1
setuptools-scm-8.0.4
mkdocs-1.5.3
hatchling-1.22.3
pluggy-1.4.0
pre_commit-3.6.2
virtualenv-20.25.1
```

And the build-system dependencies of virtualenv are

```
hatch-vcs>=0.3
hatchling>=1.17.1
```

Then `hatch-vcs` has a build-system dependency on 

```
hatchling>=1.1.0
```

which means we can't get the dependencies of `hatch-vcs` unless `hatchling` is installed.

The way I had tried to address that in #7 was by installing build dependencies before recursing. I'm not sure my original reasoning still holds, but this case does demonstrate that we can't assume that all of the dependencies will be processed in the "right" order.

**Comment by markmc** [comment]
> In the course of working on #12 I've found a circular dependency between `hatch-vcs` and `hatchling`.
> 
> ```
> langchain-0.1.13
> PyYAML-6.0.1 
> setuptools-69.2.0
> wheel-0.43.0
> pytest-8.1.1
> setuptools-scm-8.0.4
> mkdocs-1.5.3
> hatchling-1.22.3
> pluggy-1.4.0
> pre_commit-3.6.2
> virtualenv-20.25.1
> ```
>
What does the above show?

> And the build-system dependencies of virtualenv are
> 
> ```
> hatch-vcs>=0.3
> hatchling>=1.17.1
> ```
> 
> Then `hatch-vcs` has a build-system dependency on
> 
> ```
> hatchling>=1.1.0
> ```
>

So virtualenv depends on hatch-vcs and hatchling, and hatch-vcs depends on hatchling
 
> which means we can't get the dependencies of `hatch-vcs` unless `hatchling` is installed.
> 
> The way I had tried to address that in #7 was by installing build dependencies before recursing. I'm not sure my original reasoning still holds, but this case does demonstrate that we can't assume that all of the dependencies will be processed in the "right" order.

Can we not just build hatchling, hatch-vcs, and then virtualenv?

I feel like I'm missing something!

**Comment by dhellmann** [comment]
> > In the course of working on #12 I've found a circular dependency between `hatch-vcs` and `hatchling`.
> > ```
> > langchain-0.1.13
> > PyYAML-6.0.1 
> > setuptools-69.2.0
> > wheel-0.43.0
> > pytest-8.1.1
> > setuptools-scm-8.0.4
> > mkdocs-1.5.3
> > hatchling-1.22.3
> > pluggy-1.4.0
> > pre_commit-3.6.2
> > virtualenv-20.25.1
> > ```
> 
> What does the above show?

That's the dependency chain leading from langchain to virtualenv.

> 
> > And the build-system dependencies of virtualenv are
> > ```
> > hatch-vcs>=0.3
> > hatchling>=1.17.1
> > ```
> >   
> > Then `hatch-vcs` has a build-system dependency on
> > ```
> > hatchling>=1.1.0
> > ```
> 
> So virtualenv depends on hatch-vcs and hatchling, and hatch-vcs depends on hatchling
> 
> > which means we can't get the dependencies of `hatch-vcs` unless `hatchling` is installed.
> > The way I had tried to address that in #7 was by installing build dependencies before recursing. I'm not sure my original reasoning still holds, but this case does demonstrate that we can't assume that all of the dependencies will be processed in the "right" order.
> 
> Can we not just build hatchling, hatch-vcs, and then virtualenv?
> 
> I feel like I'm missing something!

I think if we build wheels for build dependencies as we encounter them, put those on a local wheel server, and let pip install from there when it tries to determine "normal" dependencies of packages, we should be OK. And now that I re-read the original description in the ticket, I think that's what you were talking about, too.
