### ISSUE TITLE
`python -m build` is not running isolated

### ISSUE THREAD

**Issue by dhellmann** [markmc/rebuilding-the-wheel#23]
We're building wheels with `python -m build`, which runs pip itself to create an isolated environment where it installs the build tools then builds the wheel. [That code](https://github.com/pypa/build/blob/main/src/build/env.py#L123) does not allow passing arguments like a local package server to use only the wheels we've already built that did _not_ require any special tools.

We could potentially configure pip through its config file to look at only the local server run as part of the toolchain. Long term we could try to add an option to pass through a different index server to the copy of pip being invoked by the build package.

At one point we were using `pip wheel` to build the packages, so we could try to resurrect that, too.

**Comment by dhellmann** [comment]
I think I have this working except for 2 (top level) dependencies that we need to bootstrap, `build` and `wheel`. Current implementation is in https://github.com/dhellmann/rebuilding-the-wheel/tree/isolated-wheel-build

**Comment by dhellmann** [comment]
Currently failing with

```
+ ./mirror-sdists.sh:71 	pip freeze
build==1.1.1
Cython==3.0.9
importlib_metadata==7.1.0
meson==1.4.0
meson-python==0.15.0
packaging==24.0
pyproject-metadata==0.7.1
pyproject_hooks==1.0.0
tomli==2.0.1
zipp==3.18.1
+ ./mirror-sdists.sh:73 	pwd
/home/dhellmann/devel/rebuilding-the-wheel/work-dir/numpy-1.26.4/numpy-1.26.4
+ ./mirror-sdists.sh:73 	python3 -m build --wheel --skip-dependency-check --no-isolation --outdir /home/dhellmann/devel/rebuilding-the-wheel/wheels-repo/downloads/ .
* Building wheel...

('\x1b[31m',)meson-python: error: Could not find ninja version 1.8.2 or newer.

ERROR Backend subprocess exited when trying to invoke build_wheel
```

meson-python wants ninja to be installed, but it's not being installed for some reason.

**Comment by markmc** [comment]
> At one point we were using `pip wheel` to build the packages, so we could try to resurrect that, too.

Yeah, I should have noticed what we were losing by going to `python -m build`

Here's what we used to do:

```
# FIXME: --no-cache-dir should be sufficient, but I don't trust it yet!
rm -rf ~/.cache/pip
...
pip -vvv --disable-pip-version-check wheel --index-url http://localhost:8000/simple ${sdist}
```

The `FIXME` part was that I wanted to back and be 100% sure that `pip wheel` wasn't picking up pre-built wheels if you used `--no-cache-dir`

Although, in the end, we'll want to be doing every individual wheel build in a pristine environment, so this won't matter so much

**Comment by markmc** [comment]
Leaving this open for:

> for 2 (top level) dependencies that we need to bootstrap, `build` and `wheel`. 

Right?

**Comment by dhellmann** [comment]
> Leaving this open for:
> 
> > for 2 (top level) dependencies that we need to bootstrap, `build` and `wheel`.
> 
> Right?

Yes, that's right.
