### ISSUE TITLE
build packages that have no sdists

### ISSUE THREAD

**Issue by dhellmann** [markmc/rebuilding-the-wheel#33]
PyTorch does not release sdists, so we wouldn't be able to build it using the existing implementation. We need a way to track special build processes for some packages.

https://github.blog/2024-02-21-how-to-stay-safe-from-repo-jacking/

We potentially need a different way to get the source (sdist, clone from git, etc.) and a different way to build the wheel once we have the source (this would let us remove the special bootstrap step for flit_core).

**Comment by markmc** [comment]
Yep, and PyTorch is definitely a non-trivial one to explore this with

https://github.com/pytorch/builder/blob/main/manywheel/build_common.sh
https://src.fedoraproject.org/rpms/python-torch/blob/rawhide/f/python-torch.spec
