### ISSUE TITLE
not handling "extra" dependencies

### ISSUE THREAD

**Issue by dhellmann** [markmc/rebuilding-the-wheel#5]
Python packages can declare optional dependencies for optional features, plugins, different modes of operating, documentation builds, and testing. These do not show up in the default list of dependencies, so they aren't being handled by the mirroring script.

https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-extras

**Comment by markmc** [comment]
Does it currently work if a package depends on an extra? I see

```
setuptools-scm[toml]>=6.2.3
```

in build-order.json

But yes ... I wanted to explore the `langchain[llms]` stack next :+1:

**Comment by dhellmann** [comment]
I haven't tried that. I noticed that my hacky implementation of setup.py projects was pulling in more dependencies than yours, and it's because I was parsing a metadata file directly with grep and ignoring the section headers that separate the extra dependencies.

I'll look at this after the SQLAlchemy issue.

**Comment by dhellmann** [comment]
In the course of testing #8, I found lots of messages like this in the output of the mirror script:

```
Ignoring pytest: markers 'extra == "test"' don't match your environment
Ignoring setuptools: markers 'extra == "test"' don't match your environment
Ignoring sphinx: markers 'extra == "docs"' don't match your environment
Ignoring sphinx: markers 'extra == "docs"' don't match your environment
Ignoring jaraco.packaging: markers 'extra == "docs"' don't match your environment
Ignoring rst.linker: markers 'extra == "docs"' don't match your environment
Ignoring furo: markers 'extra == "docs"' don't match your environment
```

**Comment by markmc** [comment]
If we take that very first example, the `wheel` package has:

```
Requires-Dist: pytest >= 6.0.0 ; extra == "test"
...
Provides-Extra: test
```

We are going to produce a `wheels-repo/` containing a `wheel-0.43.0-py3-none-any.whl` which claims it an optional "extra" called `test` and as such as user should be able to:

`
$ pip install wheel[test]
`

and this optional dependencies - `pytest >= 6.0.0` - should automatically be installed also

So, yes - we need to include dependencies for all optional extras in our repo

I could imagine it being useful to omit particular optional extras from the wheels we build - e.g. if we don't want that optional extra to be available to users of this repo - and in that case we could omit those dependencies
